### ISSUE TITLE
Cant get it to start on my Raspberry Pi 3 B+ [ARM]

### ISSUE THREAD

**Issue by Minkafighter** [0xboobface/ctbrec#126]
Hello,
I am trying to run this on a Raspberry Pi 3 B+ with the official Raspbian OS (Debian Stretch).
It already comes with Java 8, but it wont start. If I download the version with java included, i get an error that it cant run the binary because its in a wrong format (very likely because its not for ARM processors?)

If i link the start .sh java directory to /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/bin/java where my java is installed, it says that it cant find the File or Folder ...

What can I do to fix this? Can you bring out an ARM version of this?

```
java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

Thanks in advance!

**Comment by Minkafighter** [comment]
I fixed the Java install now, but now it says this:

`java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ctbrec/ui/Launcher has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
~/Desktop/ctbrec
`

What do i need to do now? Update the existing Java 8 install?

**Comment by Minkafighter** [comment]
^ Fixed it, i somehow forgot to delete the . at the start of the file location
