### ISSUE TITLE
[Lib] com.iheartradio.m3u8

### ISSUE THREAD

**Issue by bounty1342** [0xboobface/ctbrec#135]
Hello,

I'm rying to recompile it from scratch but i'm stuck with the com.iheartradio.m3u8 librairie !

I ran the following :
`mvn clean install:install-file -Dfile=/app/common/libs/open-m3u8-0.2.7-CTBREC-sources.jar  -DgroupId=com.iheartradio.m3u8 -DartifactId=open-m3u8 -Dversion=0.2.7-CTBREC -Dpackaging=jar -DgeneratePom=true
mvn clean 
mvn install `

but got stuck with :
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /app/common/src/main/java/ctbrec/Model.java:[7,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/Model.java:[8,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/Model.java:[70,90] cannot find symbol
  symbol:   class ParseException
  location: interface ctbrec.Model
[ERROR] /app/common/src/main/java/ctbrec/Model.java:[70,106] cannot find symbol
  symbol:   class PlaylistException
  location: interface ctbrec.Model
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[19,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[20,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[21,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[22,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[23,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[24,28] package com.iheartradio.m3u8 does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[25,33] package com.iheartradio.m3u8.data does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[26,33] package com.iheartradio.m3u8.data does not exist
[ERROR] /app/common/src/main/java/ctbrec/sites/mfc/MyFreeCamsModel.java:[27,33] package com.iheartradio.m3u8.data does not exist
...
```

In order to compile the librairie , i did :
git clone https://github.com/0xboobface/open-m3u8.git
gradle sourcesJar

Could you help me plz ?

**Comment by 0xboobface** [comment]
`gradle sourcesJar` creates an archive of the source files. What you want to run is `gradle install`. This creates the library jar and installs it in your local maven repository. ctbrec's maven build is then able to find it there.

**Comment by bounty1342** [comment]
Thx, made some progress, but now got an stacktrace message...

```
java.io.IOException: Couldn't parse HLS playlist:

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-STREAM-INF:BANDWIDTH=488000,NAME="FPS:30.0",CODECS="avc1.42c015,mp4a.40.2",RESOLUTION=426x240

	at ctbrec.recorder.download.HlsDownload.start(HlsDownload.java:129)
	at ctbrec.recorder.LocalRecorder$2.run(LocalRecorder.java:209)
Caused by: com.iheartradio.m3u8.ParseException: invalid attribute name: EXT-X-STREAM-INF - #EXT-X-STREAM-INF:BANDWIDTH=488000,NAME="FPS:30.0",CODECS="avc1.42c015,mp4a.40.2",RESOLUTION=426x240
	at com.iheartradio.m3u8.ParseException.create(ParseException.java:35)
	at com.iheartradio.m3u8.ParseUtil.parseAttributes(ParseUtil.java:167)
	at com.iheartradio.m3u8.MasterPlaylistLineParser$3.parse(MasterPlaylistLineParser.java:270)
        at com.iheartradio.m3u8.ExtendedM3uParser.parse(ExtendedM3uParser.java:70)
	at com.iheartradio.m3u8.PlaylistParser.parse(PlaylistParser.java:115)
	at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:317)
	at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:307)
	at ctbrec.sites.chaturbate.ChaturbateModel.getMasterPlaylist(ChaturbateModel.java:126)
	at ctbrec.sites.chaturbate.ChaturbateModel.getStreamSources(ChaturbateModel.java:138)
	at ctbrec.recorder.download.AbstractHlsDownload.getSegmentPlaylistUrl(AbstractHlsDownload.java:90)
	at ctbrec.recorder.download.HlsDownload.start(HlsDownload.java:72)
	... 1 common frames omitted
```
