### ISSUE TITLE
Chaturbate Recording Fails

### ISSUE THREAD

**Issue by gabotronix** [0xboobface/ctbrec#162]
**Describe the bug**
It looks like only Chaturbate recordings are failing. I tried recording from CAM4 and MFC, and they were both successful. The error log entries belew kept on repeating from the server console every second.

**To Reproduce**
1. Setup and configure the server side as per instructions in the README.
2. Connect to the server using the Windows client (Record Location: Remote, etc).
3. From the Ctbrec GUI, go to the Chaturbate tab.
4. Right click on any model and select Start Recording.
5. Check the log entries from the server console.

**Desktop (please complete the following information):**
 - Client OS: Windows 10 x64
 - Ctbrec Version: 1.17.1-win64-jre
 - Client / Server mode
- Server OS: CentOS 7 x64 (headless, VPS)
- Server Ctbrec Version: 1.17.1-unified

**Log**
```
12:53:32.012 [ProcessMonitor] DEBUG ctbrec.recorder.LocalRecorder - Recording terminated for model hotxxx
12:53:32.012 [pool-2-thread-1] DEBUG ctbrec.recorder.LocalRecorder - Starting post-processing for /home/ctbrec/ctbrec/hotxxx/2019-01-27_12-53
12:53:32.012 [pool-2-thread-1] DEBUG ctbrec.recorder.PlaylistGenerator - Starting playlist generation for /home/ctbrec/ctbrec/hotxxx/2019-01-27_12-53
12:53:32.012 [pool-2-thread-1] DEBUG ctbrec.recorder.PlaylistGenerator - /home/ctbrec/ctbrec/hotxxx/2019-01-27_12-53 is empty. Not going to generate a playlist
12:53:32.240 [ProcessMonitor] INFO  ctbrec.recorder.LocalRecorder - Restarting recording for model hotxxx
12:53:32.240 [ProcessMonitor] DEBUG ctbrec.recorder.LocalRecorder - Starting recording for model hotxxx
12:53:32.240 [ProcessMonitor] DEBUG ctbrec.recorder.LocalRecorder - Downloading with HlsDownload
12:53:32.241 [Thread-234] DEBUG c.r.download.AbstractHlsDownload - hotxxx stream idx: -1
12:53:32.740 [Thread-234] DEBUG ctbrec.recorder.download.HlsDownload - Waiting for last segments for hotxxx
12:53:32.740 [Thread-234] DEBUG ctbrec.recorder.download.HlsDownload - Download for hotxxx terminated
12:53:32.740 [Thread-234] ERROR ctbrec.recorder.LocalRecorder - Download for hotxxx failed. Download alive: false
ctbrec.io.HttpException: 403 - 
        at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:321)
        at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:307)
        at ctbrec.sites.chaturbate.ChaturbateModel.getMasterPlaylist(ChaturbateModel.java:126)
        at ctbrec.sites.chaturbate.ChaturbateModel.getStreamSources(ChaturbateModel.java:138)
        at ctbrec.recorder.download.AbstractHlsDownload.getSegmentPlaylistUrl(AbstractHlsDownload.java:94)
        at ctbrec.recorder.download.HlsDownload.start(HlsDownload.java:72)
        at ctbrec.recorder.LocalRecorder$2.run(LocalRecorder.java:202)
```

**Comment by 0xboobface** [comment]
Did you come to the conclusion, because of the 403? These can occur, when the model goes offline (or maybe when they go private, too).
If you experienced this error while model still was online, we might have a bug. Otherwise you can simply ignore this error.

**Comment by gabotronix** [comment]
Every model who's currently online in CB that I try to record gives out that error. Basically, I can't record anything from Chaturbate.

**Comment by sxnfxsed** [comment]
Same here, a couple hours ago some Chaturbate stuff stopped working. The thing is that there are other Chaturbate girls other than the ones below that downloaded fine (berretabang92 & priscillawtff for example). I know for sure that ashketchcum streamed and it didnt record, its just a couple of girls that are timing out when getting their status. Dunno if this is just some random ignorable error, just wanted to throw my input in since there was an issue made the same day. 

```
07:35:11.616 [OnlineMonitor] ERROR ctbrec.recorder.OnlineMonitor - Couldn't check if model aaykay_21 is online. Request timed out
07:35:21.687 [OnlineMonitor] ERROR ctbrec.recorder.OnlineMonitor - Couldn't check if model blondelashes19 is online. Request timed out
07:36:47.198 [OnlineMonitor] ERROR ctbrec.recorder.OnlineMonitor - Couldn't check if model caylin is online. HTTP Response: 521 - 
07:36:50.397 [OnlineMonitor] ERROR ctbrec.recorder.OnlineMonitor - Couldn't check if model ashketchcum is online. HTTP Response: 521 - Origin Down
```

Client OS: Windows 10
Server OS: Debian 9 Headless
Version: 1.17.1

**Comment by 0xboobface** [comment]
@sxnfxsed "521 Origin Down" is a server problem. This problem should fix itself, when the servers are back to normal.
> I know for sure that ashketchcum streamed and it didnt record
I guess this is a load balancing effect. While your browser has been connected to a working server, ctbrec was unlucky and got the broken server.

@gabotronix Not sure what's going on. I can record as usual. This has to be a temporary problem.

**Comment by sachk** [comment]
Same thing here

**Comment by Sojiro84** [comment]
I just got it as well with one of the models

The whole error log before it restarts is 

`07:34:58.281 [Thread-1651] INFO  c.r.download.MergedHlsDownload - Unexpected error while downloading dirtylalitaxx
ctbrec.io.HttpException: 404 - 
	at ctbrec.recorder.download.AbstractHlsDownload.getNextSegments(AbstractHlsDownload.java:95)
	at ctbrec.recorder.download.MergedHlsDownload.downloadSegments(MergedHlsDownload.java:189)
	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:143)
	at ctbrec.recorder.LocalRecorder$2.run(LocalRecorder.java:201)
07:34:58.282 [Thread-1651] ERROR streamer - Couldn't interrupt streamer threads
07:34:58.282 [Thread-1651] DEBUG c.r.download.MergedHlsDownload - Waiting for last segments for dirtylalitaxx
07:34:58.282 [Thread-1651] DEBUG c.r.download.MergedHlsDownload - Download for dirtylalitaxx terminated
07:34:59.011 [ProcessMonitor] DEBUG ctbrec.recorder.LocalRecorder - Recording terminated for model dirtylalitaxx
07:34:59.011 [pool-4-thread-2] DEBUG ctbrec.recorder.LocalRecorder - Starting post-processing for /mnt/Data_02/TubeDigger/dirtylalitaxx/dirtylalitaxx_2019-01-30_07-34-49_460.ts
07:34:59.011 [pool-4-thread-2] DEBUG ctbrec.recorder.LocalRecorder - Determining video length for /mnt/Data_02/TubeDigger/dirtylalitaxx/dirtylalitaxx_2019-01-30_07-34-49_460.ts
07:34:59.264 [ProcessMonitor] INFO  ctbrec.recorder.LocalRecorder - Restarting recording for model dirtylalitaxx`

I also have this issue with LiveJasmin models for about 2/3 days now. Some models work and others fail constantly. Getting a lot of zero bytes files, and the new delete recordings smaller then x seconds doesnt work here because, I guess, it is just a empty file so it can't check if it has less then zero seconds?

Using the latest 1.18 version.

LiveJasmin seems to give a 403 with the models looking in the terminal output.

```
[Thread-1296] INFO  c.r.download.MergedHlsDownload - Unexpected error while downloading SelenaBella
ctbrec.io.HttpException: 403 - Forbidden
```

Maybe it has to do with the model being in a private or other status and it fails to detect it. Gotta check that out later.

**Comment by sachk** [comment]
[Recordurbate](https://github.com/oliverjrose99/Recordurbate) is the only one that's working for me currently. It uses youtube-dl for downloading.

**Comment by bj73** [comment]
I had the empty recording folder error for Chaturbate when I updated the server version to 1.17.0, went back to 1.16.0 and it has worked fine since.

It was happening on a model that does not do Privates and _very very rarely_  does Hidden cam, (ie. 2 or 3 times a year).
