### ISSUE TITLE
Recordings on server not showing up on client

### ISSUE THREAD

**Issue by schattenkrieger** [0xboobface/ctbrec#168]
Just installed the server part on an raspi yesterday and had it set up and working. yesterday i could connect with a client from my laptop and start some recordings.
apperantly that worked over night and is still working: over night a few new folders appeared in the recordings directory on the server and when i start a new recording with the client within a few minutes a recording appears on the server.
but the finished recordings are not showing up in the client (i can only see the folders when ssh'ing in the server and checking the actual directorys)
i tried restarting the server and the client, but noting changes.

i also just saw that while the folders appear on the server and contain some files, the client just shows online of the model in the recording tab but neither recording nor paused has any checkmark

**Comment by 0xboobface** [comment]
Did you set the client to remote mode? And are you using the same version for both client and server?
![screenshot_20190203_155235](https://user-images.githubusercontent.com/40739250/52178221-db252600-27cb-11e9-8c8b-c86d9641c878.png)

**Comment by schattenkrieger** [comment]
i am running ctbrec server on an raspberry and the client on a laptop under arch linux. the server is set up according to the wiki page about systemd, and the client is just the zip file started from a shell. both are version 1.18.0. it looks like i can reach and interact with the server, because i can start a recording in the client, and a few moments later a recording appears in the appropriate folder on the server. but i can not see the recordings in the recordings tab. also the recording tab just shows that the model is online but not that i am recording.

**Comment by schattenkrieger** [comment]
just found out that the moment click on the recordings tab, i get the following errors on the client side:

`12:57:47.448 [RemoteRecorder SyncThread] ERROR ctbrec.recorder.RemoteRecorder - Couldn't synchronize with server
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at ctbrec.io.HttpClient.execute(HttpClient.java:102)
        at ctbrec.recorder.RemoteRecorder$SyncThread.syncRecordings(RemoteRecorder.java:275)
        at ctbrec.recorder.RemoteRecorder$SyncThread.run(RemoteRecorder.java:168)
Caused by: java.net.SocketException: Socket closed
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        ... 22 common frames omitted
`

**Comment by 0xboobface** [comment]
You get a read timeout, which probably means, that the pi doesn't respond fast enough. You can try the following:
* On your Arch laptop open `~/.config/ctbrec/settings.json`
* find the setting `httpTimeout` and set it to a higher value. The unit  for this value is milliseconds, so you could try something like 60,000 to give your pi a minute to respond.

**Comment by schattenkrieger** [comment]
thanks, that did the trick, would also explain why it was working in the beginning, and as soon as i had it running in "production" for one night, the next day i was getting this error.
with just a few files the raspy was fast enough to respond in time, but with a few gigs of files it was too slow
