### ISSUE TITLE
Easiest way to convert .ts to any of these formats AVI, WMV, MP4, MPG or MOV.

### ISSUE THREAD

**Issue by lordmaker** [0xboobface/ctbrec#170]
Is there any easy way to convert them ?

**Comment by Mush-r00m** [comment]
Well which platform are you on? windows? Mac? Linux?
If you are on windows. its simple, download FFmpeg static build, 32bit or 64bit depending on your OS.
https://ffmpeg.zeranoe.com/builds/
open/extract the archive, you will find ffmpeg.exe. 
Create a folder & place ffmpeg.exe in that folder.
Now open notepad & place the below text in notepad & save it as WhateverYouWant.bat

ECHO OFF
for %%a in ("*.ts") do ffmpeg -i "%%a" -c:v copy -c:a copy "%%~na.mp4"

Make sure that ffmpeg.exe & the .bat are in the same folder, then just put whatever videos you want to convert into that folder and double click the .bat file. Keep in mind this will not delete the .ts videos after converting them.

the below script will delete the .ts files after converting.

ECHO OFF
for %%a in ("*.ts") do (
ffmpeg -i "%%a" -c:v copy -c:a copy "%%~na.mp4"
del "%%~na.ts"
)
cls
ECHO.
ECHO Job done!
ECHO.
pause

This last script will convert all .ts video files in the subfolders of the "ctbrec" folder where all recording are stored. DO NOT run this last script while models are currently being recorded.

echo off
TITLE %~nx0
for /r %%F in (*.ts) do (
    ffmpeg.exe  -i "%%F" -c:v copy -c:a copy "%%~dpnF.mp4"
    if not errorlevel 1 if exist "%%~dpnF.mp4" del /q "%%F"
)


simply place this last script into the main folder where all the models videos are stored & only run it when NOT currently recording. this will delete all .ts files after recording.

**Comment by Al3601** [comment]
> Well which platform are you on? windows? Mac? Linux?
> If you are on windows. its simple, download FFmpeg static build, 32bit or 64bit depending on your OS.
> https://ffmpeg.zeranoe.com/builds/
> open/extract the archive, you will find ffmpeg.exe.
> Create a folder & place ffmpeg.exe in that folder.
> Now open notepad & place the below text in notepad & save it as WhateverYouWant.bat
> 
> ECHO OFF
> for %%a in ("*.ts") do ffmpeg -i "%%a" -c:v copy -c:a copy "%%~na.mp4"
> 
> Make sure that ffmpeg.exe & the .bat are in the same folder, then just put whatever videos you want to convert into that folder and double click the .bat file. Keep in mind this will not delete the .ts videos after converting them.
> 
> the below script will delete the .ts files after converting.
> 
> ECHO OFF
> for %%a in ("*.ts") do (
> ffmpeg -i "%%a" -c:v copy -c:a copy "%%~na.mp4"
> del "%%~na.ts"
> )
> cls
> ECHO.
> ECHO Job done!
> ECHO.
> pause
> 
> This last script will convert all .ts video files in the subfolders of the "ctbrec" folder where all recording are stored. DO NOT run this last script while models are currently being recorded.
> 
> echo off
> TITLE %~nx0
> for /r %%F in (*.ts) do (
> ffmpeg.exe -i "%%F" -c:v copy -c:a copy "%%~dpnF.mp4"
> if not errorlevel 1 if exist "%%~dpnF.mp4" del /q "%%F"
> )
> 
> simply place this last script & ffmpeg into the main folder where all the models videos are stored & only run it when NOT currently recording. this will delete all .ts files after converting..

Thank you, is it working in the same way with "playlist.m3u8" generated on the server version for linux?
already checked the others issues here, the bash scripts provided didn't work for me :/

**Comment by Al3601** [comment]
> What I use on two Linux VPS's:
> 
> Note, I only use root account, (I'm lazy), after creating the MP4 it deletes the date sub-folder, not the model folder, (because bad things happen if you delete the model folder and it's still recording into another date sub-folder).
> 
> This is using 1.16.0, (1.17.0/1 wasn't recording anything and I haven't updated to 1.18.0).
> 
> ```
> #!/bin/bash
> 
> # $1 parent directory (model name)
> # $2 directory (date)
> # $3 model name
> # $4 site name
> # $5 unixtime
> 
> # get the filename without path
> FILE=$(echo $2/playlist.m3u8)
> 
> # format unixtime to human readable
> TIME=$(date --date="@$5" +%Y%m%d-%H%M)
> 
> # define filename of end result
> MP4=$(echo "/root/ctbrec/captures/$3_$TIME.mp4")
> 
> # remux ts to mp4
> ffmpeg -i $FILE -c:v copy -c:a copy -bsf:a aac_adtstoasc $MP4
> 
> # delete the directory of the recording
> rm -r $2
> ```

thank you! 

same as others i get this error : 
`date: invalid date ‘@’
/playlist.m3u8: No such file or directory
rm: missing operand

`
i run the 1.17.0 version

**Comment by bj73** [comment]
Add the following lines after the **#!/bin/bash** line:

**echo $1
echo $2
echo $3
echo $4
echo $5**

ie.
~~~
#!/bin/bash

echo $1
echo $2
echo $3
echo $4
echo $5

# $1 parent directory (model name)
# $2 directory (date)
# $3 model name
# $4 site name
# $5 unixtime

# get the filename without path
FILE=$(echo $2/playlist.m3u8)

# format unixtime to human readable
TIME=$(date --date="@$5" +%Y%m%d-%H%M)

# define filename of end result
MP4=$(echo "/root/ctbrec/captures/$3_$TIME.mp4")

# remux ts to mp4
ffmpeg -i $FILE -c:v copy -c:a copy -bsf:a aac_adtstoasc $MP4

# delete the directory of the recording
rm -r $2
~~~

Do they show what you expect?
Is there a date folder under the model folder?

And, as I mentioned, 1.17.0 wasn't recording for me, (on CB), so it didn't generate any playlist, (so I reverted to 1.16.0).

The above is working fine on Debian 8 x64 and Ubuntu 16.04 x64 VPS's.

**Comment by Al3601** [comment]
same results im running on Debian 9 x64 (1.17.0 docker version)

```
:~/cams/ctb/video/Fit_Gal$ ./convert.sh





date: invalid date ‘@’
ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
/playlist.m3u8: No such file or directory
rm: missing operand
Try 'rm --help' for more information.

```

**Comment by bj73** [comment]
How exactly are you running the script?

Because it's meant to be run as a post-processing job, so in your **server.json** file (**server/client setup**) or **settings.json** (**standalone mode**) you should have a line that reads similarly to:

**"postProcessing": "/root/ctbrec/post.sh",**

Naturally, change the **/root/ctbrec/post.sh** to point to wherever you have the script.


If you just want to do it from the CLI then change to the directory with the playlist:

ffmpeg -i playlist.m3u8 -c:v copy -c:a copy -bsf:a aac_adtstoasc filename.mp4

Read up on ffmpeg if you want some different codec/container output.

**Comment by Al3601** [comment]
well, it seems i can't add the post-processing script to ctbrec, here is what i tested : 

- add  "postProcessing": "/root/.config/ctbrec/convert.sh",  to server.json uploaded to /home/XXX/cams/ctb/app/config (i have the docker version)

- uploaded with ftp to /home/XXX/cams/ctb/app/config/convert.sh  + chmod 775

- after test with error, changed to "postProcessing": "/home/XXX/cams/ctb/app/config/convert.sh"



same results : 

'''

15:45:21.276 [Thread-15] DEBUG ctbrec.recorder.download.HlsDownload - Download for AmaraGray terminated


15:45:21.276 [pool-2-thread-2] DEBUG ctbrec.recorder.LocalRecorder - Starting post-processing for /root/ctbrec/AmaraGray/2019-02-04_15-40


15:45:21.278 [pool-2-thread-2] DEBUG ctbrec.recorder.PlaylistGenerator - Starting playlist generation for /root/ctbrec/AmaraGray/2019-02-04_15-40


15:45:30.478 [pool-2-thread-2] DEBUG ctbrec.recorder.PlaylistGenerator - Finished playlist generation for /root/ctbrec/AmaraGray/2019-02-04_15-40


15:45:30.484 [pool-2-thread-2] DEBUG ctbrec.recorder.PlaylistGenerator - Generated playlist looks good


15:45:30.485 [pool-2-thread-2] DEBUG ctbrec.recorder.LocalRecorder - Running [/root/.config/ctbrec/convert.sh, /root/ctbrec/AmaraGray, /root/ctbrec/AmaraGray/2019-02-04_15-40, AmaraGray, Streamate, 1549294853]


15:45:30.488 [pool-2-thread-2] ERROR ctbrec.recorder.LocalRecorder - Error in process thread


java.io.IOException: Cannot run program "/root/.config/ctbrec/convert.sh": error=2, No such file or directory


	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)


	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)


	at java.base/java.lang.Runtime.exec(Runtime.java:589)


	at java.base/java.lang.Runtime.exec(Runtime.java:491)


	at ctbrec.recorder.LocalRecorder.postprocess(LocalRecorder.java:236)


	at ctbrec.recorder.LocalRecorder.lambda$createPostProcessor$5(LocalRecorder.java:769)


	at ctbrec.recorder.LocalRecorder.lambda$stopRecordingProcess$1(LocalRecorder.java:217)


	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)


	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)


	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)


	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at java.base/java.lang.Thread.run(Thread.java:835)


Caused by: java.io.IOException: error=2, No such file or directory


	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)


	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)


	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)


	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)


	... 11 common frames omitted

'''

what i am doing wrong ?

**Comment by Al3601** [comment]
the problem is, i  cannot add the convert.sh to the container, i tested with 

i tried do remove the actual container and mount a new one with the convert.sh, but not worked.

'''
docker run -d -p 8699:8080 -v /home/XXX/cams/ctb/app/config:/root/.config/ctbrec/ -v /home/XXX/cams/ctb/app/config/convert.sh:/root/.config/ctbrec/convert.sh -v /home/XXX/cams/ctb/video:/root/ctbrec bounty1342/ctbrec
'''
i added the file manually

'''

docker cp convert.sh 678a5808b8576b60fe6b21e294e3994ed6dc92416d62e207956f8321888ab55c:/root/.config/ctbrec/convert.sh
docker cp 678a5808b8576b60fe6b21e294e3994ed6dc92416d62e207956f8321888ab55c:/root/.config/ctbrec/convert.sh convert.sh
'''

didn't work, so for now i just switched off the docker version and revert back to lastest server-linux.sh and everithing worked like a charm!
thank you @bj73  for the bash script

**Comment by bj73** [comment]
> thank you @bj73 for the bash script

It's just a tweak of the script CTBRec came with to change the filename format to my preferred, put it in the base captures directory, and to not delete the model directory, (since there might still be recording going on).

**Comment by Leviathan1509** [comment]
I know of 2 easy ways on Windows, both without re-encoding and both are GUI, no knowledge of command line needed:

1. Open the .ts file in the open source software Avidemux, select the output formar - .avi, .mp4 or even .mkv and save the file without re-encoding,

2. Use the free XMedia Recode - select the mp4 container - or any other for that matter - in the video tab select copy instead of convert, the same in the audio tab, press the Add to Queue button, then the Encode button and you have an MP4 in a few seconds.

**Comment by bj73** [comment]
The Transport Stream files are only a couple of hundred kB each, there are possibly hundreds/thousands of them captured by the CTBRec server, each of them only being a second or two long.

It's not as simple as just loading "the" .ts file into an editor and remuxing/transcoding to another container/codec format.

You need to be able to load the generated playlist, (playlist.m3u8), which contains a list of all the Transport Stream segments in the correct order _or_ use an editor that recognises there's a sequence and appends them all.

AVIDemux will append all the segments _if_ you load all of the TS files at once, (eg. Drag'n'Drop them on the AVIDemux window), it doesn't understand playlists.

XMedia Recode can load the playlist but doesn't seem to be able to append media files.
