### ISSUE TITLE
response code: 403

### ISSUE THREAD

**Issue by ceohk** [0xboobface/ctbrec#3]
2018-07-06 10:18:41,358 ERROR [Thread-22] c.r.LocalRecorder [LocalRecorder.java:124] Download failed. Download alive: false
java.io.IOException: Couldn't download segment
	at ctbrec.recorder.download.HlsDownload.start(HlsDownload.java:130)
	at ctbrec.recorder.LocalRecorder$1.run(LocalRecorder.java:122)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: 

Could you help ?

**Comment by 0xboobface** [comment]
Did you try different models? This mostly happens, if a model is offline or just went offline. And with offline I mean, that the room is not public anymore (e.g. offline, private show etc.).

**Comment by ceohk** [comment]
The problem is solved using VPN. :(
