### ISSUE TITLE
Detailed Instructions on how to run this script on macOS

### ISSUE THREAD

**Issue by Asynchr0nous** [0xboobface/ctbrec#43]
Download and extract ctbrec-1.6.0-linux.zip from release section (or whatever the lastest version is)

Download .tar Java Runtime Enrionment (JRE) from https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html (if link doesn't work quick google) and extract it to your desired location. Note: JDK/OpenJDK don't work

Open terminal and run this command: `touch ~/.bash_profile; open ~/.bash_profile`

This will open up text editor simply paste this: `export JAVA_HOME="/path/to/your/jre/Contents/Home"` and save

Close/restart your terminal for changes to take affect

To run the script do:

`cd /path/to/ctbrec`

then:

`./ctbrec.sh`

**Note: It would be great if some kind of instructions can be shown for noobs in README.md**

**Comment by 0xboobface** [comment]
Thank you for the detailed instructions. The main reason, I didn't include a version for macos, is my lack of macs. So I can't really test it. I would try to generate a macos distribution, if you are willing to test it and give me some feedback (or even fix problems and send me the changes)

**Comment by Asynchr0nous** [comment]
Yeah sure, I don't mind testing and where ever possible try to fix any issues (though i'm not a great programmer lol)

**Comment by 0xboobface** [comment]
I just uploaded 1.7.0 with a version for macos. Would be nice, if you could test, if the script is working.

**Comment by ItsN3rdy** [comment]
I appreciate all the work yall do 😃

**Comment by 0xboobface** [comment]
@ItsN3rdy is it now working for you, too?

**Comment by ItsN3rdy** [comment]
Yes i am running 1.7.0 perfectly now. Glad you added max resolution option too!

**Comment by Densch25** [comment]
I get a `Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
` when I execute ctbrec.sh on my Mac with both the versions (ctbrec-1.11.0-macos-jre and ctbrec-1.11.0-macos). I have also tried versions 1.10.0 1.9.0 and 1.8.0. and I got the same error message for every single one of them (including -jre).
I have tried fixing this problem on my own, but after 3 days of failure I have no clue how to successfully get that program to work. Any help would be appreciated.

**Comment by 0xboobface** [comment]
Is that all you get on console? This doesn't really help in finding the problem.

**Comment by Densch25** [comment]
The Full Error message is: `Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1316)
	at java.base/java.util.Properties.setProperty(Properties.java:225)
	at java.base/java.lang.System.setProperty(System.java:892)
	at ctbrec.io.HttpClient.loadProxySettings(HttpClient.java:53)
	at ctbrec.io.HttpClient.reconfigure(HttpClient.java:115)
	at ctbrec.io.HttpClient.<init>(HttpClient.java:45)
	at ctbrec.ui.CamrecApplication$3.<init>(CamrecApplication.java:261)
	at ctbrec.ui.CamrecApplication.createHttpClient(CamrecApplication.java:261)
	at ctbrec.ui.CamrecApplication.start(CamrecApplication.java:75)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
~
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
`
Thanks a lot.

**Comment by 0xboobface** [comment]
Did you configure a proxy? It looks like your proxy settings are bogus.

**Comment by Densch25** [comment]
That fixed it, thanks a lot!
