### ISSUE TITLE
Can't Install On Ubuntu

### ISSUE THREAD

**Issue by jjis2018** [0xboobface/ctbrec#53]
Trying to install the GUI on Ubuntu Budgie. Have Java installed, as suggested in another post I downloaded JavaFX and put it int eh ctbrec folder. I get this trying to run it:

java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
20:47:27,242 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:47:27,243 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
20:47:27,243 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/d/ctbrec/ctbrec-1.8.0-final.jar!/logback.xml]
20:47:27,253 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@124c278f - URL [jar:file:/home/d/ctbrec/ctbrec-1.8.0-final.jar!/logback.xml] is not of type file
20:47:27,327 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:47:27,336 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [jar:file:/home/d/ctbrec/ctbrec-1.8.0-final.jar!/logback.xml] 
20:47:27,336 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
20:47:27,337 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:47:27,339 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
20:47:27,342 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:47:27,385 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
20:47:27,386 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
20:47:27,388 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:47:27,389 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [ctbrec.log]
20:47:27,390 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(ctbrec.log,true) call failed. java.io.FileNotFoundException: ctbrec.log (Permission denied)
	at java.io.FileNotFoundException: ctbrec.log (Permission denied)
	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at ctbrec.ui.Launcher.<clinit>(Launcher.java:8)
20:47:27,391 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
20:47:27,391 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
20:47:27,391 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
20:47:27,391 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ctbrec.LoggingInterceptor] to INFO
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ctbrec.recorder.Chaturbate] to INFO
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ctbrec.recorder.server.HlsServlet] to INFO
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ctbrec.recorder.server.RecorderServlet] to INFO
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ctbrec.io.CookieJarImpl] to INFO
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ctbrec.ui.ThumbOverviewTab] to DEBUG
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty] to INFO
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [streamer] to ERROR
20:47:27,392 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:47:27,393 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2ddc8ecb - Registering current configuration as safe fallback point

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at ctbrec.ui.Launcher.main(Launcher.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassL

**Comment by 0xboobface** [comment]
Unfortunately Java 11 doesn't come with JavaFX anymore. You can either install JavaFX, or try an older version from java.oracle.com. I recommend the latest Java 8 release (at the moment 8u192).
Also, make sure you have write permission for the ctbrec directory. Otherwise the logfile cannot be written.

**Comment by jjis2018** [comment]
Got it working by install Java 8

**Comment by 0xboobface** [comment]
The next version will include JavaFx, so that you can run it with Java 11. I also created a Linux version, which includes Java 11, so that ctbrec should run out of the box on almost any machine (hopefully :smiley: )
