### ISSUE TITLE
Request: change base URL

### ISSUE THREAD

**Issue by reyaz006** [0xboobface/ctbrec#81]
Problem:
chaturbate.com is blocked in my region by some ISP and this affects me sometimes.

Fact:
while chaturbate.com is unreachable without proxy, en.chaturbate.com is reachable and seems working just fine.

Feature request:
Allow me to change the base URL that is being used to access certain service. I clearly see that I can do that in browser without proxy, so there should be no problems.

**Comment by reyaz006** [comment]
While we are at it...

Would it be possible to process different internal layers of services separately? For example, the main website may be blocked, while internal streaming cdn/services could be working. Even though I may have access to VPN or proxies, I wouldn't want to pass the whole video data stream through additional network node which I can't really control. Instead, I may want to try and process the website and its api through a proxy, get direct links to streams I need and then proceed to connect to them directly.

Perhaps global changes would be needed for this to work. E.g. 2 systems may be introduced:
- debugging information which would report which domain or IP address is being accessed.
- settings layer which would allow to set up proxy usage for any specific domain/path or IP address.
So any time a connection attempt is made, it would respect the user settings and connect through a proxy or directly.

**Comment by 0xboobface** [comment]
> Allow me to change the base URL that is being used

I can add a setting for Chaturbate. 

> While we are at it...

Everything is possible, but in my opinion, this is out of scope of ctbrec. Maybe you can do that with a proxy, which does rule-based URL rewriting.

**Comment by reyaz006** [comment]
>Everything is possible, but in my opinion, this is out of scope of ctbrec. Maybe you can do that with a proxy, which does rule-based URL rewriting.

Makes sense. However I know only one proxy provider with such a proxy, and that proxy is in PAC format.

**Comment by reyaz006** [comment]
> I can add a setting for Chaturbate.

I've just noticed that absolutely same applies to MFC. Default URL doesn't work and MFC doesn't load in application, but en.myfreecams.com works.

Here is the log if needed

> 2018-12-02 14:11:55,620 ERROR [JavaFX Application Thread] c.u.CamrecApplication [CamrecApplication.java:85] Error while initializing site MyFreeCams
> org.json.JSONException: A JSONObject text must begin with '{' at 2 [character 1 line 2]
> 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
> 	at org.json.JSONObject.<init>(JSONObject.java:214)
> 	at org.json.JSONObject.<init>(JSONObject.java:357)
> 	at ctbrec.sites.mfc.ServerConfig.<init>(ServerConfig.java:32)
> 	at ctbrec.sites.mfc.MyFreeCamsClient.start(MyFreeCamsClient.java:88)
> 	at ctbrec.sites.mfc.MyFreeCams.init(MyFreeCams.java:27)
> 	at ctbrec.ui.CamrecApplication.start(CamrecApplication.java:83)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by reyaz006** [comment]
It seems to work for CTB, thanks.

With MFC, it didn't solve my issue. The error is all the same for it:

> 2018-12-03 08:38:11,200 ERROR [OkHttp http://xchat126.myfreecams.com:8080/...] c.s.m.MyFreeCamsClient [MyFreeCamsClient.java:175] MFC websocket failure: 404 Not Found
> java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
> 	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:228)
> 	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:195)
> 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
> 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

If I request http://xchat126.myfreecams.com:8080/ in another tool - I get `HTTP/1.1 200 OK`
If I add 3 dots like in the log - I get `HTTP/1.1 404 Not Found`

**Comment by reyaz006** [comment]
Consider the following:
- I can use a different tool for MFC named MFCRecorder without proxy and it can record streams (it has other issues but it can connect to the service). Its functionality is based on websockets too iirc.
- The 404 error is not normal at all.
- The reported URL does not look normal at all. Why would anything be located at `myfreecams.com:8080/...` ? The three dots look like there should be something meaningful instead of them there.

I do not record any model from MFC. Just having it enabled in options triggers this error. And MFC tab remains empty.

**Comment by 0xboobface** [comment]
I will have a look at MFCRecorder and see, what it does differently. The url is shortened by the logging library. Thus the three dots. The full URL is http://xchat126.myfreecams.com:8080/fcsl

**Comment by reyaz006** [comment]
Pardon me, I've made a mistake when I've reported that MFCRecorder works without proxy. While it's true, I need to mention that I've also had to change the website URL to IP address in tool's .py files, to work around ISP blocking the website by URL.

Anyway, I see that MFCRecorder first fetches the "main" config file (`/_js/serverconfig.js`), which contains a collection of exact "xchat" numbers. Perhaps choosing a random number is not how it should work.

>Edit: Do you get the error every time or only sporadically?

Not sure since I'm running ctbrec on a remote PC too. I may have seen the MFC tab displaying properly at some point. I just didn't restart the app many times to test it.

**Comment by 0xboobface** [comment]
> Anyway, I see that MFCRecorder first fetches the "main" config file (`/_js/serverconfig.js`), which contains a collection of exact "xchat" numbers. Perhaps choosing a random number is not how it should work.

ctbrec loads the same file and chooses a random server from it, because MFC's own client does it the same way:
```JavaScript
Chat.GetRandomChatServer = function() {
        if (Ext && Ext.getCmp && Ext.getCmp("dwcs")) {
            var e = Ext.getCmp("dwcs").getValue();
            if (e) return e
        }
        if ("flashsocket" == ServerSocket.type) {
            var t = Math.round(Math.random() * (Chat.chatServers.length - 1));
            return Chat.chatServers[t]
        }
        if (1 == Chat.chatServers.length) return Chat.chatServers[0];
// the important stuff starts here
        var i = [];
        for (var t in Chat.chatServers) Chat.chatServers[t] == ServerSocket.protocol && i.push(t);
        if (0 == i.length) return Log("Couldn't find any servers for protocol type " + ServerSocket.protocol), "chat2";
        var t = Math.round(Math.random() * (i.length - 1));
        return i[t]
    }
```
ctbrec does not do the protocol check (which I should add), but that does not explain, why it is not working for you, because xchat126 has the right protocol.

**Comment by reyaz006** [comment]
I've found the cause. Http proxy. When it's enabled, MFC will return '404 Not Found'.

I've found a tool named pacproxy which creates local proxy with rules set by remote .pac proxy, and it works great for Chaturbate in ctbrec (also it lets me have access to models who block my region). It also works fine in browser on myfreecams.com.

For MFC, either proxy support needs to be fixed, or it needs and option to not use proxy for MFC (socket-based?) connections.

**Comment by reyaz006** [comment]
I'd really prefer proxy support to be fixed since it'll allow me to have access to many more models.
