### ISSUE TITLE
Problems with the new "space check" feature

### ISSUE THREAD

**Issue by Locosam** [0xboobface/ctbrec#86]
Hi,
First of all, thanks for a great tool.
Since the latest update of the release, I was unable to record anything at all, even though I set no value for it.
The drive Im recording to is a mounted drive, not a local drive.
```
  at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
  at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
  at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
  at java.base/sun.nio.fs.WindowsFileStore.create(WindowsFileStore.java:94)
  at java.base/sun.nio.fs.WindowsFileSystemProvider.getFileStore(WindowsFileSystemProvider.java:483)
  at java.base/java.nio.file.Files.getFileStore(Files.java:1487)
  at ctbrec.recorder.LocalRecorder.getRecordingsFileStore(LocalRecorder.java:784)
  at ctbrec.recorder.LocalRecorder.getFreeSpaceBytes(LocalRecorder.java:779)
  at ctbrec.recorder.LocalRecorder.enoughSpaceForRecording(LocalRecorder.java:790)
  at ctbrec.recorder.LocalRecorder.startRecordingProcess(LocalRecorder.java:154)
  at ctbrec.recorder.LocalRecorder.access$1200(LocalRecorder.java:51)
  at ctbrec.recorder.LocalRecorder$OnlineMonitor.run(LocalRecorder.java:440)
2018-11-29 23:15:48,005 WARN [ProcessMonitor] c.r.LocalRecorder [LocalRecorder.java:350] Couldn't check free space left
java.nio.file.FileSystemException: G:\Drive\AF\rec: The directory is not a subdirectory of the root directory.
```

**Comment by 0xboobface** [comment]
Is it an external drive or a network share? Also, the top of the error message is missing. Can you post a little bit more or attach a file?

**Comment by 0xboobface** [comment]
I changed the code, so that everything still should work, even if the space check fails. But I still would like to fix the cause.
